wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.19
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      4: 3.8.5
      5: 0.10.19
      8:
      - 1
batch_size:
  desc: null
  value: 1024
dropout:
  desc: null
  value: 0.5
forward:
  desc: null
  value: false
hidden_states:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.00025
n_neighbors:
  desc: null
  value: 9
